FROM jupyter/datascience-notebook:latest
LABEL description = "Dockerfile for jupyter"
MAINTAINER "Rui Benfeitas" rui.benfeitas@scilifelab.se
USER root

# Use bash as shell
SHELL ["/bin/bash", "-c"]

# Set working directory
WORKDIR /home/jovyan/project

# Install vim
RUN apt-get update
RUN apt-get install -y vim pip git

# Install conda
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

# Copy and install the Conda environment
COPY environment_jupyter.yml ./
RUN conda config --set channel_priority strict \
    && mamba env update --name base --file environment_jupyter.yml \
    && mamba clean --all --force-pkgs-dirs --yes

# Copy github repo files
COPY workshop/ workshop/

# Start Bash shell by default
#CMD /bin/bash

# Start jupyter
CMD start-notebook.sh